require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BriefCommentsController do

  # This should return the minimal set of attributes required to create a valid
  # BriefComment. As you add validations to BriefComment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all brief_comments as @brief_comments" do
      brief_comment = BriefComment.create! valid_attributes
      get :index
      assigns(:brief_comments).should eq([brief_comment])
    end
  end

  describe "GET show" do
    it "assigns the requested brief_comment as @brief_comment" do
      brief_comment = BriefComment.create! valid_attributes
      get :show, :id => brief_comment.id
      assigns(:brief_comment).should eq(brief_comment)
    end
  end

  describe "GET new" do
    it "assigns a new brief_comment as @brief_comment" do
      get :new
      assigns(:brief_comment).should be_a_new(BriefComment)
    end
  end

  describe "GET edit" do
    it "assigns the requested brief_comment as @brief_comment" do
      brief_comment = BriefComment.create! valid_attributes
      get :edit, :id => brief_comment.id
      assigns(:brief_comment).should eq(brief_comment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BriefComment" do
        expect {
          post :create, :brief_comment => valid_attributes
        }.to change(BriefComment, :count).by(1)
      end

      it "assigns a newly created brief_comment as @brief_comment" do
        post :create, :brief_comment => valid_attributes
        assigns(:brief_comment).should be_a(BriefComment)
        assigns(:brief_comment).should be_persisted
      end

      it "redirects to the created brief_comment" do
        post :create, :brief_comment => valid_attributes
        response.should redirect_to(BriefComment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved brief_comment as @brief_comment" do
        # Trigger the behavior that occurs when invalid params are submitted
        BriefComment.any_instance.stub(:save).and_return(false)
        post :create, :brief_comment => {}
        assigns(:brief_comment).should be_a_new(BriefComment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BriefComment.any_instance.stub(:save).and_return(false)
        post :create, :brief_comment => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested brief_comment" do
        brief_comment = BriefComment.create! valid_attributes
        # Assuming there are no other brief_comments in the database, this
        # specifies that the BriefComment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BriefComment.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => brief_comment.id, :brief_comment => {'these' => 'params'}
      end

      it "assigns the requested brief_comment as @brief_comment" do
        brief_comment = BriefComment.create! valid_attributes
        put :update, :id => brief_comment.id, :brief_comment => valid_attributes
        assigns(:brief_comment).should eq(brief_comment)
      end

      it "redirects to the brief_comment" do
        brief_comment = BriefComment.create! valid_attributes
        put :update, :id => brief_comment.id, :brief_comment => valid_attributes
        response.should redirect_to(brief_comment)
      end
    end

    describe "with invalid params" do
      it "assigns the brief_comment as @brief_comment" do
        brief_comment = BriefComment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BriefComment.any_instance.stub(:save).and_return(false)
        put :update, :id => brief_comment.id, :brief_comment => {}
        assigns(:brief_comment).should eq(brief_comment)
      end

      it "re-renders the 'edit' template" do
        brief_comment = BriefComment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BriefComment.any_instance.stub(:save).and_return(false)
        put :update, :id => brief_comment.id, :brief_comment => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested brief_comment" do
      brief_comment = BriefComment.create! valid_attributes
      expect {
        delete :destroy, :id => brief_comment.id
      }.to change(BriefComment, :count).by(-1)
    end

    it "redirects to the brief_comments list" do
      brief_comment = BriefComment.create! valid_attributes
      delete :destroy, :id => brief_comment.id
      response.should redirect_to(brief_comments_url)
    end
  end

end
